# Generated by Django 5.1.1 on 2024-09-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='myApp1/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 9, 6, 11, 0, 12, 911209, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('EC', 'Electronic'), ('BP', 'Beauty & Personal Care'), ('TG', 'Toys & Games ')], max_length=2)),
            ],
        ),
    ]
